class ApiLink {
  // static const String server = 'https://localhost:7159/api';
  static const String server = 'https://smartneighboorhood.runasp.net/api';
  static const String login = '$server/Auth/Login';
  static const String getAllBlockes = '$server/Blocks/GetAll';
  static const String getAllProjects = '$server/Projects/GetAll';
  static const String getAllProjectCatgories = '$server/ProjectCatgories/GetAll';
  static const String deleteProject = '$server/Projects/Delete';
  static const String addProject = '$server/Projects/Add';
  static const String updateProject = '$server/Projects/Update';
  static const String getProjectTeams = '$server/Projects/GetProjectTeam';
  static const String getProjectBlockFamilies = '$server/Projects/GetProjectBlocksWithBeneficiaryFamilies';
  static const String assignTeamToProject = '$server/Projects/assign-team';
  static const String assignFamilyToProject = '$server/Projects/assign-family';
  static const String removeTeamFromeProject = '$server/Projects/remove-team';
  static const String removeFamilyFromeProject = '$server/Projects/remove-family';
  static const String getAllTeams = '$server/Teams/GetAll';
  static const String addTeam = '$server/Teams/Add';
  static const String updateTeam = '$server/Teams/Update';
  static const String deleteTeam = '$server/Teams/Delete';
  static const String getTeamById = '$server/Teams/GetById';
  static const String getProjectsByTeamId = '$server/Teams/by-team';
  static const String addTeamMember = '$server/TeamMembers/Add';
  static const String updateTeamMember = '$server/TeamMembers/Update';
  static const String deleteTeamMember = '$server/TeamMembers/Delete';
  static const String getAllTeamRoles = '$server/TeamRole/GetAll';

  static const String getAllFamilyCategories = '$server/FamilyCatgory/GetAll';
  static const String getAllMemberFamilyRoles =
      '$server/MemberFamilyRole/getAllMemberTypes';
  static const String getAllFamilyTypes = '$server/FamilyTypes/GetAll';
  static const String addBlocke = '$server/Blocks/Add';
  static const String updateBlocke = '$server/Blocks/Update';
  static const String deleteBlocke = '$server/Blocks/Delete';
  static const String addFamily = '$server/Family/Add';
  static const String deleteFamily = '$server/Family/Delete';
  static const String getAllFamily = '$server/Family/GetAll';
  static const String updateFamily = '$server/Family/Update';
  static const String addFamilyMember = '$server/Family/AddMember';
  static const String addExistingPersonToFamily = '$server/FamilyMembers/Add';
  static const String getFamilyMembers = '$server/FamilyMembers/GetAll';
  static const String getFamilyDetailes = '$server/Family/GetDetailes';
  static const String getBlockDetails = '$server/Blocks/GetDetails';
  static const String addNewPerson = '$server/Person/Add';
  static const String deletePerson = '$server/Person/Delete';
  static const String updatePerson = '$server/Person/Update';
  static const String getAllPepole = '$server/Person/GetAll';
  static const String getPersonById = '$server/Person/GetById';
  static const String getAllConflict = '$server/ConflictCase/GetAll';
  static const String addConflict = '$server/ConflictCase/Add';
  static const String updateConflict = '$server/ConflictCase/Update';
  static const String deleteConflict = '$server/ConflictCase/Delete';
  static const String getAllConfilctCaseTypes = '$server/ConfilctCaseType/GetAll';
  static const String getConflictCasesByFamilyMember = '$server/ConflictCase/ByFamilyMember';

  static const String sendEmail = '$server/Auth/Password-reset/send-code';
  static const String sendConfirmationCode = '$server/Auth/Password-reset/verify-code';
  static const String sendNewPassword = '$server/Auth/Password-reset/confirm';
}
