import '../datasources/conflict_local_datasource.dart';
import '../datasources/conflict_remote_datasource.dart';
import '../models/conflict.dart';
import '../models/conflict_type.dart';

/// Repository for conflict data management
/// Implements offline-first pattern: read from local, write locally and optionally sync
class ConflictRepository {
  final ConflictLocalDataSource _localDataSource;
  final ConflictRemoteDataSource _remoteDataSource;

  ConflictRepository({
    required ConflictLocalDataSource localDataSource,
    required ConflictRemoteDataSource remoteDataSource,
  }) : _localDataSource = localDataSource,
       _remoteDataSource = remoteDataSource;

  // ============================================================================
  // CONFLICT OPERATIONS - OFFLINE FIRST
  // ============================================================================

  /// Get all conflicts (from local database)
  /// Returns locally stored conflicts for offline support
  Future<List<Conflict>> getAllConflicts() async {
    return await _localDataSource.getAllConflicts();
  }

  /// Get conflict by ID (from local database)
  Future<Conflict?> getConflictById(int id) async {
    return await _localDataSource.getConflictById(id);
  }

  /// Get conflicts by resolution status (from local database)
  Future<List<Conflict>> getConflictsByStatus(bool isResolved) async {
    return await _localDataSource.getConflictsByStatus(isResolved);
  }

  /// Get conflicts by type (from local database)
  Future<List<Conflict>> getConflictsByType(int conflictTypeId) async {
    return await _localDataSource.getConflictsByType(conflictTypeId);
  }

  /// Get conflicts involving a specific person (from local database)
  Future<List<Conflict>> getConflictsByPerson(int personId) async {
    return await _localDataSource.getConflictsByPerson(personId);
  }

  /// Search conflicts (from local database)
  Future<List<Conflict>> searchConflicts(String query) async {
    return await _localDataSource.searchConflicts(query);
  }

  /// Get upcoming conflicts (from local database)
  Future<List<Conflict>> getUpcomingConflicts() async {
    return await _localDataSource.getUpcomingConflicts();
  }

  /// Create new conflict
  /// Saves to local database immediately with sync_status='pending'
  /// User can trigger sync later via sync button
  Future<Conflict> createConflict({
    required int conflictTypeId,
    required String conflictTypeName,
    required int firstPartyId,
    required String firstPartyName,
    required int secondPartyId,
    required String secondPartyName,
    required String managerName,
    required String title,
    required String notes,
    DateTime? sessionDate,
    bool isResolved = false,
    String? imagePath,
    String imageUrl = '',
  }) async {
    // Create conflict object for local database
    final conflict = Conflict(
      id: 0, // Will be auto-generated by database
      title: title,
      conflictTypeId: conflictTypeId,
      conflictTypeName: conflictTypeName,
      managerName: managerName,
      firstPartyId: firstPartyId,
      firstPartyName: firstPartyName,
      secondPartyId: secondPartyId,
      secondPartyName: secondPartyName,
      notes: notes,
      imageUrl: imageUrl,
      sessionDate: sessionDate,
      isResolved: isResolved,
      syncStatus: 'pending', // Mark for sync
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    // Save to local database
    final localId = await _localDataSource.insertConflict(conflict);

    // Return the saved conflict with local ID
    final savedConflict = conflict.copyWith(id: localId);
    return savedConflict;
  }

  /// Update existing conflict
  /// Updates local database and marks as pending for sync
  Future<Conflict> updateConflict({
    required int id,
    required int conflictTypeId,
    required String conflictTypeName,
    required int firstPartyId,
    required String firstPartyName,
    required int secondPartyId,
    required String secondPartyName,
    required String managerName,
    required String title,
    required String notes,
    DateTime? sessionDate,
    bool? isResolved,
    String? imagePath,
    String? imageUrl,
  }) async {
    // Get existing conflict from local DB
    final existingConflict = await _localDataSource.getConflictById(id);

    if (existingConflict == null) {
      throw Exception('Conflict not found with id: $id');
    }

    // Update conflict with new values
    final updatedConflict = existingConflict.copyWith(
      title: title,
      conflictTypeId: conflictTypeId,
      conflictTypeName: conflictTypeName,
      managerName: managerName,
      firstPartyId: firstPartyId,
      firstPartyName: firstPartyName,
      secondPartyId: secondPartyId,
      secondPartyName: secondPartyName,
      notes: notes,
      sessionDate: sessionDate,
      isResolved: isResolved,
      imageUrl: imageUrl ?? existingConflict.imageUrl,
      syncStatus: 'pending', // Mark for sync
      updatedAt: DateTime.now(),
    );

    // Update in local database
    await _localDataSource.updateConflict(updatedConflict);

    return updatedConflict;
  }

  /// Delete conflict
  /// Soft deletes in local database (marks as deleted, doesn't remove)
  /// Will be deleted from server on next sync
  Future<void> deleteConflict(int id) async {
    await _localDataSource.deleteConflict(id);
  }

  /// Update conflict resolution status
  Future<void> updateResolutionStatus(int id, bool isResolved) async {
    await _localDataSource.updateConflictResolutionStatus(id, isResolved);
  }

  // ============================================================================
  // SYNC OPERATIONS - MANUAL TRIGGER
  // ============================================================================

  /// Sync pending conflicts with server
  /// Uploads local changes and downloads server updates
  /// Called when user presses sync button
  Future<SyncResult> syncConflicts() async {
    int uploadedCount = 0;
    int downloadedCount = 0;
    final errors = <String>[];

    try {
      // STEP 1: Upload pending conflicts to server
      final pendingConflicts = await _localDataSource.getPendingConflicts();

      for (final conflict in pendingConflicts) {
        try {
          if (conflict.deletedAt != null) {
            // Handle deleted conflicts
            if (conflict.serverId != null) {
              await _remoteDataSource.deleteConflict(conflict.serverId!);
            }
          } else if (conflict.serverId != null) {
            // Update existing conflict on server
            final updatedConflict = await _remoteDataSource.updateConflict(
              id: conflict.serverId!,
              conflictTypeId: conflict.conflictTypeId,
              firstPartyId: conflict.firstPartyId,
              secondPartyId: conflict.secondPartyId,
              title: conflict.title,
              notes: conflict.notes,
              sessionDate: conflict.sessionDate,
              isResolved: conflict.isResolved,
            );

            // Mark as synced in local DB
            await _localDataSource.markConflictAsSynced(
              conflict.id,
              serverId: updatedConflict.id,
            );
          } else {
            // Create new conflict on server
            final createdConflict = await _remoteDataSource.createConflict(
              conflictTypeId: conflict.conflictTypeId,
              firstPartyId: conflict.firstPartyId,
              secondPartyId: conflict.secondPartyId,
              title: conflict.title,
              notes: conflict.notes,
              sessionDate: conflict.sessionDate,
              isResolved: conflict.isResolved,
            );

            // Mark as synced and save server ID
            await _localDataSource.markConflictAsSynced(
              conflict.id,
              serverId: createdConflict.id,
            );
          }

          uploadedCount++;
        } catch (e) {
          errors.add('Failed to sync conflict "${conflict.title}": $e');
        }
      }

      // STEP 2: Download all conflicts from server
      try {
        final serverConflicts = await _remoteDataSource.getAllConflicts();

        for (final serverConflict in serverConflicts) {
          // Convert API response to database format
          final dbData = {
            'title': serverConflict.title,
            'conflict_type_id': serverConflict.conflictTypeId,
            'conflict_type_name': serverConflict.conflictTypeName,
            'manager_name': serverConflict.managerName,
            'first_party_id': serverConflict.firstPartyId,
            'first_party_name': serverConflict.firstPartyName,
            'second_party_id': serverConflict.secondPartyId,
            'second_party_name': serverConflict.secondPartyName,
            'notes': serverConflict.notes,
            'image_url': serverConflict.imageUrl,
            'session_date': serverConflict.sessionDate?.toIso8601String(),
            'is_resolved': serverConflict.isResolved ? 1 : 0,
            'server_id': serverConflict.id,
            'sync_status': 'synced',
          };

          await _localDataSource.upsertConflictFromServer(dbData);
          downloadedCount++;
        }
      } catch (e) {
        errors.add('Failed to download conflicts from server: $e');
      }

      return SyncResult(
        success: errors.isEmpty,
        uploadedCount: uploadedCount,
        downloadedCount: downloadedCount,
        errors: errors,
      );
    } catch (e) {
      return SyncResult(
        success: false,
        uploadedCount: uploadedCount,
        downloadedCount: downloadedCount,
        errors: [...errors, 'Sync failed: $e'],
      );
    }
  }

  /// Get count of pending conflicts (for UI badge)
  Future<int> getPendingCount() async {
    final pendingConflicts = await _localDataSource.getPendingConflicts();
    return pendingConflicts.length;
  }

  // ============================================================================
  // CONFLICT TYPE OPERATIONS
  // ============================================================================

  /// Get all conflict types (from local database)
  /// For dropdowns/pickers - uses cached data
  Future<List<ConflictType>> getAllConflictTypes() async {
    var types = await _localDataSource.getAllConflictTypes();

    // If no types in local DB, fetch from server and cache
    if (types.isEmpty) {
      types = await refreshConflictTypes();
    }

    return types;
  }

  /// Refresh conflict types from server
  /// Called on first launch or when user manually refreshes
  Future<List<ConflictType>> refreshConflictTypes() async {
    try {
      final serverTypes = await _remoteDataSource.getAllConflictTypes();

      // Save to local database
      for (final type in serverTypes) {
        final dbData = {
          'name': type.name,
          'server_id': type.id,
          'sync_status': 'synced',
        };
        await _localDataSource.upsertConflictTypeFromServer(dbData);
      }

      return await _localDataSource.getAllConflictTypes();
    } catch (e) {
      // On error, return what's in local DB (offline support)
      return await _localDataSource.getAllConflictTypes();
    }
  }

  /// Search conflict types
  Future<List<ConflictType>> searchConflictTypes(String query) async {
    return await _localDataSource.searchConflictTypes(query);
  }
}

/// Result of sync operation
class SyncResult {
  final bool success;
  final int uploadedCount;
  final int downloadedCount;
  final List<String> errors;

  SyncResult({
    required this.success,
    required this.uploadedCount,
    required this.downloadedCount,
    required this.errors,
  });

  String get message {
    if (success) {
      return 'Sync successful: ↑$uploadedCount uploaded, ↓$downloadedCount downloaded';
    } else {
      return 'Sync completed with errors: ${errors.length} error(s)';
    }
  }
}
